name: 'Setup R Environment'
description: 'Standard setup for R package workflows (requires checkout first)'
inputs:
  extra-packages:
    description: 'Extra packages to install'
    required: false
    default: ''
  needs:
    description: 'Dependencies needs'
    required: false
    default: ''
  r-version:
    description: 'R version'
    required: false
    default: 'release'
  http-user-agent:
    description: 'HTTP user agent'
    required: false
    default: 'release'
runs:
  using: "composite"
  steps:
    - uses: r-lib/actions/setup-pandoc@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2.11.4

    - uses: r-lib/actions/setup-r@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2.11.4
      with:
        r-version: ${{ inputs.r-version }}
        http-user-agent: ${{ inputs.http-user-agent }}
        use-public-rspm: true

    - uses: r-lib/actions/setup-r-dependencies@6f6e5bc62fba3a704f74e7ad7ef7676c5c6a2590 # v2.11.4
      with:
        extra-packages: ${{ inputs.extra-packages }}
        needs: ${{ inputs.needs }}
